# Site settings
name: Luigi Russo
title: Luigi Russo | Computer Engineer
description: Computer engineer passionate about cryptography and writing code.
url: https://lrusso96.github.io/
baseurl: ""
email: russol@eurecom.fr
cover: https://lrusso96.github.io/img/og.jpg
logo: https://lrusso96.github.io/img/logo-black.png
resume: https://raw.githubusercontent.com/lrusso96/cv/master/main.pdf
social:
  - title: email
    url: mailto:russol@eurecom.fr
  - title: instagram
    url: https://instagram.com/_u/luigi.russo19
  - title: github
    url: https://github.com/lrusso96

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
